spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/cafecrowd}
    username: ${DB_USER:cafecrowd}
    password: ${DB_PASSWORD:cafecrowd}
  jpa:
    show-sql: true

springdoc:
  swagger-ui:
    enabled: true
