INSERT INTO cafes (id, name, available, lat, lng, intro, address, thumbnail_url, photos, naver_place_url) VALUES
('cafe-1', '국민카페', true, 37.5409, 127.0696,
 '광장동 골목 끝 조용한 동네 카페',
 '서울 광진구 광장동 111-22',
 'https://cdn.cafecrowd.example.com/cafes/cafe-1/thumb.webp',
 '["https://cdn.cafecrowd.example.com/cafes/cafe-1/1.webp","https://cdn.cafecrowd.example.com/cafes/cafe-1/2.webp"]'::jsonb,
 'https://map.naver.com/v5/search/국민카페'),
('cafe-2', '한강뷰 라운지', false, 37.5395, 127.0712,
 '한강이 보이는 통창 카페',
 '서울 광진구 광장동 200-1',
 'https://cdn.cafecrowd.example.com/cafes/cafe-2/thumb.webp',
 '["https://cdn.cafecrowd.example.com/cafes/cafe-2/1.webp"]'::jsonb,
 'https://map.naver.com/v5/search/한강뷰라운지'),
('cafe-3', '브루잉랩', true, 37.5421, 127.0683,
 '핸드드립 전문',
 '서울 광진구 자양동 50-3',
 'https://cdn.cafecrowd.example.com/cafes/cafe-3/thumb.webp',
 '[]'::jsonb,
 'https://map.naver.com/v5/search/브루잉랩'),
('cafe-4', '책읽는 고양이', true, 37.5388, 127.0731,
 '책 + 디저트 + 고양이',
 '서울 광진구 구의동 320-9',
 'https://cdn.cafecrowd.example.com/cafes/cafe-4/thumb.webp',
 '["https://cdn.cafecrowd.example.com/cafes/cafe-4/1.webp","https://cdn.cafecrowd.example.com/cafes/cafe-4/2.webp","https://cdn.cafecrowd.example.com/cafes/cafe-4/3.webp"]'::jsonb,
 'https://map.naver.com/v5/search/책읽는고양이'),
('cafe-5', '루프탑 88', false, 37.5417, 127.0721,
 '루프탑 야경 명소',
 '서울 광진구 자양동 88-8',
 'https://cdn.cafecrowd.example.com/cafes/cafe-5/thumb.webp',
 '[]'::jsonb,
 'https://map.naver.com/v5/search/루프탑88');
